# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170401_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
