# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170504_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('fat_content', models.IntegerField(blank=True, null=True)),
                ('protein_content', models.IntegerField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='management.Animal')),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
    ]
