# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170521_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.IntegerField()),
                ('krahmal', models.IntegerField(blank=True, default=0, null=True)),
                ('sugar', models.IntegerField(blank=True, default=0, null=True)),
                ('calcii', models.IntegerField(blank=True, default=0, null=True)),
                ('fosfor', models.IntegerField(blank=True, default=0, null=True)),
                ('magnie', models.IntegerField(blank=True, default=0, null=True)),
                ('cali', models.IntegerField(blank=True, default=0, null=True)),
                ('sera', models.IntegerField(blank=True, default=0, null=True)),
                ('jelezo', models.IntegerField(blank=True, default=0, null=True)),
                ('med', models.IntegerField(blank=True, default=0, null=True)),
                ('cink', models.IntegerField(blank=True, default=0, null=True)),
                ('marganec', models.IntegerField(blank=True, default=0, null=True)),
                ('kobalt', models.IntegerField(blank=True, default=0, null=True)),
                ('iod', models.IntegerField(blank=True, default=0, null=True)),
                ('karotin', models.IntegerField(blank=True, default=0, null=True)),
                ('vit_e', models.IntegerField(blank=True, default=0, null=True)),
                ('vit_d', models.IntegerField(blank=True, default=0, null=True)),
                ('vit_a', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
