# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20170523_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_last_sex',
            field=models.DateField(blank=True, null=True),
        ),
    ]
