# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20170523_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.Farm'),
        ),
    ]
