# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='norm',
            name='animal_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.AnimalType'),
            preserve_default=False,
        ),
    ]
