# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_norm_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='norm',
            name='Perev_proteine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='norm',
            name='Siro_proteine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='norm',
            name='sir_cletchatka',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='norm',
            name='sir_jir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='norm',
            name='sol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соль'),
        ),
        migrations.AddField(
            model_name='norm',
            name='suh_veschestvo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
