# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20170524_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmgroup',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AnimalType'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='farm', chained_model_field='farm', default=1, on_delete=django.db.models.deletion.CASCADE, to='management.FarmGroup'),
            preserve_default=False,
        ),
    ]
