# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20170526_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasschet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Farm')),
                ('foods', models.ManyToManyField(to='management.Food')),
                ('group', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='farm', chained_model_field='farm', on_delete=django.db.models.deletion.CASCADE, to='management.FarmGroup')),
            ],
        ),
    ]
