# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rasschet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasschet',
            name='foods',
        ),
    ]
