# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_rasschet_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasschetFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Food')),
                ('rasschet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Rasschet')),
            ],
        ),
    ]
