# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_rasschetfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasschet',
            name='norm',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='animal_type', chained_model_field='group__type', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Norm'),
        ),
    ]
