# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_auto_20170526_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasschet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AnimalType'),
        ),
        migrations.AlterField(
            model_name='rasschet',
            name='norm',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='management.Norm'),
        ),
    ]
