# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20170526_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasschet',
            name='norm',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group__type', chained_model_field='animal_type', on_delete=django.db.models.deletion.CASCADE, to='management.Norm'),
        ),
    ]
