# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20170526_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmgroup',
            name='type',
        ),
    ]
