# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_remove_farmgroup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='сorm',
            new_name='corm',
        ),
        migrations.RenameField(
            model_name='norm',
            old_name='сorm',
            new_name='corm',
        ),
    ]
