# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_auto_20170527_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Тип животного', 'verbose_name_plural': 'Типы животных'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'Ферма', 'verbose_name_plural': 'Фермы'},
        ),
        migrations.AlterModelOptions(
            name='farmgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Корм', 'verbose_name_plural': 'Корма'},
        ),
        migrations.AlterModelOptions(
            name='milkyield',
            options={'verbose_name': 'Удой молока', 'verbose_name_plural': 'Удои молока'},
        ),
        migrations.AlterModelOptions(
            name='norm',
            options={'verbose_name': 'Норма', 'verbose_name_plural': 'Нормы'},
        ),
        migrations.AlterModelOptions(
            name='rasschet',
            options={'verbose_name': 'Рассчет', 'verbose_name_plural': 'Рассчеты'},
        ),
        migrations.AddField(
            model_name='rasschet',
            name='month',
            field=models.CharField(blank=True, choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=30, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='rasschet',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='rasschet',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Farm', verbose_name='Ферма'),
        ),
        migrations.AlterField(
            model_name='rasschet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AnimalType', verbose_name='Тип животных'),
        ),
    ]
